### ISSUE TITLE
[Refactor] Auth-Practice 이메일 로그인 Rx로 리펙토링 

### ISSUE THREAD

**Issue by pcsoyeon** [zanzanbari/zanzan-sokyte#10]
## 💡 Issue
Auth-Practice 프로젝트의 이메일 로그인 뷰에 해당하여 Rx로 리펙토링을 진행합니다. 

## 📝  todo
- [ ] ViewController와 View 분리
- [ ] 이벤트 처리 Rx로 리펙
- [ ] 서버 연결 Rx로 리펙
