### ISSUE TITLE
[Feat] 왈 히스토리 UI 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [zanzanbari/zanzan-sokyte#12]
## 💡 Issue
솝텀 프로젝트 왈 히스토리 UI를 구현합니다. 

## 📝  todo
- [x] 전체 UI 구현
- [x] 섹션 별 스와이프 구현
- [ ] 동적 셀 높이 구현 
- [ ] 길게 누르기 인터랙션 구현 
- [x] 더미데이터 추가 (.json)
