### ISSUE TITLE
[Feat] 에셋 추가 및 디자인 시스템 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [zanzanbari/zanzan-sokyte#3]
## 💡 Issue
컬러, 폰트, 아이콘 등을 포함한 에셋 추가 및 카카오T 디자인시스템을 적용합니다. 

## 📝  todo
- [x] 컬러 에셋 추가
- [x] 폰트 에셋 추가
- [x] 아이콘, 버튼 이미지 에셋 추가
- [x] 디자인시스템 구현
