### ISSUE TITLE
[Feat] 지도 -> 검색 화면 전환 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [zanzanbari/zanzan-sokyte#5]
## 💡 Issue
지도 화면에서 하단 모달 창을 탭하였을 때, 위로 올라오는 검색 화면의 전환을 구현합니다. 

## 📝  todo
- [x] 지도 화면에서 하단 모달 창 UI 구현
- [x] 하달 모달 UI 탭 했을 때 검색 화면으로 전환 구현
- [x] 각 화면의 디테일 UI 구현 (지도 제외)
